name: walisan_app_andro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  barcode_widget: ^2.0.4
  font_awesome_flutter: ^10.7.0
  http: ^1.2.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  intl: ^0.19.0
  pdf: ^3.12.0
  printing: ^5.14.3


dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Menambahkan folder assets untuk logo dan gambar
  assets:
    - assets/images/LOGOOO.png
    - assets/images/kaligrafi.png
